# Generated by Django 4.1.3 on 2022-11-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
