# Generated by Django 4.1.3 on 2022-11-29 19:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to=core.models.upload_image),
        ),
    ]
